version: '3'

services:
  database:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootsecretpassword
    ports:
      - "3306:3306"
    volumes:
      - ./models/init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "127.0.0.1:8080:80" 
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: mysqlrootsecretpassword
    depends_on:
      - database
  app:
    build: .
    container_name: app_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - database